// Dependency
const mongoose = require('mongoose');

// Schema
const userSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, required: true },
});

// const userSchema = new mongoose.Schema({
//   username: { type: String, required: true, unique: false },
//   password: { type: String, required: false }, //not required because of anonymous users
//   currentGameID: { type: String },
//   enemyID: { type: mongoose.ObjectId },
//   totalGames: { type: Number, default: 0, min: [0, 'Invalid number'] },
//   wins: { type: Number, default: 0, min: [0, 'Invalid number'] },
//   carrier: { type: Number, default: 5, min: [0, 'Invalid number'] },
//   battleship: { type: Number, default: 4, min: [0, 'Invalid number'] },
//   cruiser: { type: Number, default: 3, min: [0, 'Invalid number'] },
//   submarine: { type: Number, default: 3, min: [0, 'Invalid number'] },
//   destroyer: { type: Number, default: 2, min: [0, 'Invalid number'] },
//   yourBoard: {
//     A: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     B: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     C: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     D: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     E: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     F: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     G: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     H: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     I: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     J: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//   },
//   enemyBoard: {
//     A: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     B: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     C: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     D: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     E: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     F: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     G: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     H: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     I: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//     J: {
//       1: { type: String, default: 0 },
//       2: { type: String, default: 0 },
//       3: { type: String, default: 0 },
//       4: { type: String, default: 0 },
//       5: { type: String, default: 0 },
//       6: { type: String, default: 0 },
//       7: { type: String, default: 0 },
//       8: { type: String, default: 0 },
//       9: { type: String, default: 0 },
//       10: { type: String, default: 0 },
//     },
//   },
// });

// Model export
module.exports = mongoose.model('User', userSchema);
